include("r3frac.jl")
include("r3mv.jl")
include("LatticeVars.jl")
include("AtomicVars.jl")
include("AtomicSpeciesVars.jl")
include("MuffinTinRadialVars.jl")
include("APWLOVars.jl")
include("readspecies.jl")
include("mtdmin.jl")
include("checkmt.jl")
include("genrmesh.jl")

include("polynm.jl")
include("splint.jl")
include("wsplint.jl")
include("wsplintp.jl")