include("r3frac.jl")
include("r3mv.jl")
include("LatticeVars.jl")
include("AtomicVars.jl")
include("AtomicSpeciesVars.jl")
include("MuffinTinRadialVars.jl")
include("APWLOVars.jl")
include("readspecies.jl")
include("mtdmin.jl")
include("checkmt.jl")
include("genrmesh.jl")
include("radnucl.jl")
include("potnucl.jl")

include("XC_funcs/XC_x_slater.jl")
include("XC_funcs/XC_c_vwn.jl")

include("polynm.jl")
include("splint.jl")
include("splintwp.jl")
include("wsplint.jl")
include("wsplintp.jl")

include("solve_atom.jl")
include("rdirac.jl")
include("rdiracint.jl")